SF_News_Portal-main/News_Portal/News_Portal/urls.py
"""
Конфигурация URL для проекта News_Portal.

Список `urlpatterns` направляет URL-адреса в представления. Для получения дополнительной информации см.:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Примеры:
Представления функций
    1. Добавить импорт: из представлений импорта my_app
    2. Добавьте URL-адрес в urlpatterns: path('', views.home, name='home')
Представления на основе классов
    1. Добавить импорт: from other_app.views import Home
    2. Добавьте URL-адрес в urlpatterns: path('', Home.as_view(), name='home')
Включение другой конфигурации URL
    1. Импортируйте функцию include(): из django.urls import include, path
    2. Добавьте URL-адрес в urlpatterns: path('blog', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),  # запросы от пользователей по ссылкам, которые
    # начинаются с /accounts/
]

SF_News_Portal-main/News_Portal/news/urls.py
from django.urls import path
from . import views
from .views import NewsList, NewsDetail, Search, NewsEdit, NewsDelete, ArticleEdit, ArticleDelete

app_name = 'news'

urlpatterns = [
    path('', views.Start_Padge, name='Start'),  # URL-шаблон Стартовой страницы
    path('search/', Search.as_view(), name='search'),  # URL-шаблон Поисковой страницы
    path('news/', NewsList.as_view(), name='news_list'),  # URL-шаблон для списка новостей
    path('news/<int:pk>/', NewsDetail.as_view(), name='news_detail'),  # URL-шаблон для списка новостей
    path('article/', views.article_list, name='article_list'),  # URL-шаблон для списка статей
    path('articles/<int:post_id>/', views.article_detail, name='article_detail'),  # URL-шаблон для статьи
    path('news/create/', views.NewsCreate.as_view(), name='news_create'),  # URL-шаблон для создания новостей
    path('news/<int:pk>/edit/', NewsEdit.as_view(), name='news_edit'),  # URL-шаблон для редактирования новостей
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),  # URL-шаблон для удаления новостей
    path('articles/create/', views.ArticleCreate.as_view(), name='articles_create'),  # URL-шаблон для создания статьи
    path('articles/<int:pk>/edit/', ArticleEdit.as_view(), name='article_edit'),  # URL-шаблон для редактирования статьи
    path('articles/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),  # URL-шаблон для удаления статьи

]

SF_News_Portal-main/News_Portal/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse


# Создавайте свои модели здесь.
class Author(models.Model):
    """
    Метод update_rating() вычисляет суммарный рейтинг каждой статьи автора,
    умножает его на 3, а затем складывает с суммарным рейтингом всех комментариев автора
    и комментариев к статьям автора.
    Результат сохраняется в поле rating объекта Author
    """

    autUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAut = models.SmallIntegerField(default=0)

    def update_rating(self):
        # Вычисление суммарного рейтинга статей автора
        post_sum = self.post_set.aggregate(postRating=Sum('rating'))  # Сбор всех данных определённого поля автора
        temp_sum_p = 0
        temp_sum_p += post_sum.get('postRating')
        # Вычисление суммарного рейтинга комментариев автора
        comment_sum = self.autUser.comment_set.aggregate(commentRating=Sum('rating'))
        temp_sum_c = 0
        temp_sum_c += comment_sum.get('commentRating')

        self.ratingAut = temp_sum_p * 3 + temp_sum_c
        self.save()

    # для удобного отображения на странице администратора
    def __str__(self):
        return self.autUser.username


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    # для отображения имён вместо объектов
    def __str__(self):
        return self.name


class Post(models.Model):
    """
    Метод preview() возвращает начало статьи длиной 124 символа с многоточием в конце
    Методы like() и dislike() увеличивают/уменьшают рейтинг на единицу.
    """
    ARTICLE = 'AR'
    NEWS = 'NW'
    CATEGOY_CHOICES = (
        ('AR', 'Статья'),
        ('NW', 'Новость'),
    )
    author = models.ForeignKey(Author, on_delete=models.CASCADE)  # Поле Автор
    type = models.CharField(max_length=2, choices=CATEGOY_CHOICES, default=ARTICLE)  # Поле выбора новость / статья
    creationDate = models.DateTimeField(auto_now_add=True)  # Авто добавление даты создания
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    content = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.content[:123]} ...'

    # для удобного отображения на странице администратора
    def __str__(self):
        return self.title

    # какую страницу нужно открыть после создания
    @staticmethod
    def get_absolute_url():
        return reverse('Start')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    """
    Методы like() и dislike() увеличивают/уменьшают рейтинг на единицу.
    """
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    # для удобного отображения на странице администратора
    def __str__(self):
        return self.text

SF_News_Portal-main/News_Portal/news/forms.py
from django import forms
from .models import Post


class NewsForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['postCategory', 'title', 'content']


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['postCategory', 'title', 'content']

SF_News_Portal-main/News_Portal/news/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .filters import PostFilter
from .forms import NewsForm, ArticleForm
from .models import Post, Category

"""
get_object_or_404 - используется для получения объекта из базы данных по заданным условиям. 
Если объект не найден, то функция вызывает исключение `Http404`, и возвращает страницу с ошибкой 404.
"""


# ====== Стартовая страница ============================================================================================
def Start_Padge(request):
    news = Post.objects.filter(type='NW').order_by('-creationDate')[:4]
    return render(request, 'flatpages/Start.html', {'news': news})

# ====== Новости =======================================================================================================
class NewsList(ListView):
    paginate_by = 10
    model = Post
    template_name = 'news/news_list.html'
    context_object_name = 'news'

    def get_queryset(self):
        queryset = super().get_queryset().filter(type='NW')
        return queryset.order_by('-creationDate')


class NewsDetail(DetailView):
    model = Post
    template_name = 'news/news_detail.html'
    context_object_name = 'post'


class NewsCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    raise_exception = True
    model = Post
    form_class = NewsForm
    template_name = 'news_create.html'
    success_url = '/'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.type = 'NW'
        post.author = self.request.user.author
        post.save()
        return super().form_valid(form)


class NewsEdit(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    raise_exception = True
    model = Post
    form_class = NewsForm
    template_name = 'news_edit.html'
    success_url = '/'


class NewsDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    permission_required = ('news.add_post',)
    raise_exception = True
    model = Post
    template_name = 'news_delete.html'
    success_url = '/'


# ====== Статьи ========================================================================================================
def article_list(request):
    article = Post.objects.filter(type='AR').order_by('-creationDate')  # Фильтруем только статьи
    # и сортируем по убыванию даты
    paginator = Paginator(article, 2)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'news/article_list.html', {'articles': articles})


def article_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'news/article_detail.html', {'post': post})


class ArticleCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    raise_exception = True
    model = Post
    form_class = ArticleForm
    template_name = 'article_create.html'
    success_url = '/'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.type = 'AR'
        post.author = self.request.user.author
        post.save()
        return super().form_valid(form)


class ArticleEdit(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    raise_exception = True
    model = Post
    form_class = ArticleForm
    template_name = 'article_edit.html'
    success_url = '/'


class ArticleDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    raise_exception = True
    model = Post
    template_name = 'article_delete.html'
    success_url = '/'


# ====== Поиск =========================================================================================================
class Search(ListView):
    model = Post
    template_name = 'flatpages/search.html'
    context_object_name = 'search'
    filterset_class = PostFilter
    paginate_by = 7

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        context['categories'] = Category.objects.all()  # Получение всех категорий
        return context

SF_News_Portal-main/News_Portal/news/templates/news/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать статью</h1>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
  <h1>Удаление</h1>
  <p>Вы уверены, что хотите удалить эту статью?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/article_detail.html
{% extends 'flatpages/default.html' %}

{% load cenzura %}

{% block content %}
    <h1>{{ post.title|censor }}</h1>
    <p>{{ post.creationDate|date:"d.m.Y" }}</p>
    <p>{{ post.content|censor }}</p>
<!-- А здесь доступ для каждой ссылки теперь будем проверять отдельно -->
    {% if perms.news.change_post %}
    <hr>
        <a href="{% url 'news:article_edit' pk=post.id %}">Изменить</a>
    {% endif %}
    {% if perms.news.delete_post %}
    <hr>
        <a href="{% url  'news:article_delete' post.id %}">Удалить</a>
    {% endif %}
<hr />
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Редактирование</h1>
<hr>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/article_list.html
{% extends 'flatpages/default.html' %}

{% load cenzura %}

{% block content %}
    <h2>Список статей</h2>
    <hr />

    <!-- Будем проверять права пользователя -->
    {% if perms.news.add_post %}
    <h3><a href="{% url 'news:articles_create' %}">Добавить статью</a></h3>
    <hr />
    {% endif %}

    <ul>
        {% for post in articles %}
            <h3>{{ post.title|censor }}</h3>
            <p>{{ post.creationDate|date:"d.m.Y" }}</p>
            <p>{{ post.content|censor|slice:":20" }} {{"..."}}</p>
            <a href="{% url 'news:article_detail' post.id %}">Читать далее</a>
        {% endfor %}
    </ul>

    <hr />

    <!-- Постраничная навигация -->
    <div class="pagination justify-content-center">
        {% if articles.has_previous %}
            <a class="page-link" href="?page=1">&laquo;-</a>
        {% endif %}

        {% if articles.previous_page_number != 1 %}
            <a class="page-link" href="?page={{ articles.previous_page_number }}">{{ articles.previous_page_number }}</a>
        {% endif %}

        <span class="page-link">{{ articles.number }}</span>

        {% if articles.has_next %}
            {% if paginator.num_pages != articles.next_page_number %}
                <a class="page-link" href="?page={{ articles.next_page_number }}">{{ articles.next_page_number }}</a>
            {% endif %}
            <a class="page-link" href="?page={{ articles.paginator.num_pages }}">-&raquo;</a>
        {% endif %}
    </div>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать новость</h1>
<hr>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление</h1>
<hr>
 <p>Вы уверены, что хотите удалить эту новость?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/news_detail.html
{% extends 'flatpages/default.html' %}

{% load cenzura %}

{% block content %}
    <h1>{{ post.title|censor }}</h1>
    <p>{{ post.creationDate|date:"d.m.Y" }}</p>
    <p>{{ post.content|censor }}</p>
    <!-- А здесь доступ для каждой ссылки теперь будем проверять отдельно -->
    {% if perms.news.change_post %}
    <hr>
        <a href="{% url 'news:news_edit' pk=post.id %}">Изменить</a>
    {% endif %}
    {% if perms.news.delete_post %}
    <hr>
        <a href="{% url  'news:news_delete' post.id %}">Удалить</a>
    {% endif %}
<hr />
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Редактирование</h1>
<hr>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
  </form>
{% endblock %}

SF_News_Portal-main/News_Portal/news/templates/news/news_list.html
{% extends 'flatpages/default.html' %}

{% load cenzura %}

{% block content %}
    <h2>Список новостей</h2>
<hr />
    <!--Будем проверять права пользователя-->
    {% if perms.news.add_post %}
    <h3><a href="{% url 'news:news_create' %}">Добавить новость</a></h3>
    <hr>
    {% endif %}
    <ul>
        {% for post in news %}
            <h3>{{ post.title|censor }}</h3>
            <p>{{ post.creationDate|date:"d.m.Y" }}</p>
            <p>{{ post.content|censor|slice:":20" }} {{"..."}}</p>
            <a href="{% url 'news:news_detail' post.id %}">Читать далее</a>
        {% endfor %}
    </ul>
<hr />
    {% if page_obj.has_previous %}
    <!-- Для каждой ссылки пагинации указываем обработку через новый тег -->
        <a href="?page=1">&laquo; 1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock %}